package net.technolords.tools.artificer.input;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.technolords.tools.artificer.TestSupport;

public class ArtifactManagerTest extends TestSupport {
    private static final Logger LOGGER = LoggerFactory.getLogger(ArtifactManagerTest.class);

    @Test
    public void testAnalyseArtifact() {
        // TODO: implement this test

        /** test cases
            * #1 - analyse non-Jar files, verify if exception thrown
            * #2 - analyse malformed jar file, verify which file in jar is malformed to ignore or separate
            * #3 - analyse a jar file generated by WAR plugin
            //reference : https://discuss.gradle.org/t/the-war-plugin-generates-war-files-which-are-not-valid-jar-files-and-cannot-be-unpacked-with-e-g-the-command-line-jar-utility/1247
         */

        LOGGER.info("I am a placeholder");
    }
}